#!/usr/bin/env bash


echo "Compiling Monitor, Server and Client..."

cargo build --manifest-path /home/shadow-starter/simple_tcp_server_client/project-tonic/Cargo.toml
cargo build --manifest-path /home/shadow-starter/Documents/syncronous_tcp_server_client/proj_sync/Cargo.toml

# first argument is the path to shadow
if [ "$#" -ge 1 ]; then
    echo "Prepending $1 to PATH"
    export PATH="$1:${PATH}"
fi




if [ -d "shadow.data" ]; then
  echo "  "
  printf '%s\n' "Removing directory shadow.data"
  rm -rf "shadow.data"
  echo "  "
fi

shadow shadow.yaml > hugo.log

echo;
for file in shadow.data/hosts/*/*.stdout;
  do 
    echo "##########################################"
    echo $file 
    echo;
    cat $file; 
    echo "##########################################"
    echo;
  done