general:
  stop_time: 12 sec
  seed: 1
  parallelism: 1
  bootstrap_end_time: 0 sec
  log_level: info
  heartbeat_interval: 1 sec
  data_directory: shadow.data
  template_directory: null
  progress: false
  model_unblocked_syscall_latency: true
network:
  graph:
    type: 1_gbit_switch
  use_shortest_path: true
experimental:
  use_sched_fifo: false
  use_explicit_block_message: false
  use_syscall_counters: true
  use_object_counters: true
  use_preload_libc: true
  use_preload_openssl_rng: true
  use_preload_openssl_crypto: false
  preload_spin_max: 0
  use_memory_manager: true
  use_shim_syscall_handler: true
  use_cpu_pinning: true
  runahead: 1 ms
  use_dynamic_runahead: false
  socket_send_buffer: 131072 B
  socket_send_autotune: true
  socket_recv_buffer: 174760 B
  socket_recv_autotune: true
  interface_qdisc: fifo
  use_legacy_working_dir: false
  host_heartbeat_log_level: info
  host_heartbeat_log_info:
  - node
  host_heartbeat_interval: 1 sec
  strace_logging_mode: off
  max_unapplied_cpu_latency: 1 μs
  unblocked_syscall_latency: 1 μs
  unblocked_vdso_latency: 10 ns
  use_extended_yaml: false
  scheduler: thread-per-core
hosts:
  client:
    network_node_id: 0
    processes:
    - path: h_client
      args: '8888'
      environment: ''
      quantity: 1
      start_time: 6 sec
      stop_time: null
    ip_addr: null
    quantity: 1
    bandwidth_down: null
    bandwidth_up: null
    options:
      log_level: null
      pcap_directory: null
      pcap_capture_size: 65535 B
  monitor:
    network_node_id: 0
    processes:
    - path: h_monitor
      args: ''
      environment: ''
      quantity: 1
      start_time: 0 sec
      stop_time: null
    ip_addr: null
    quantity: 1
    bandwidth_down: null
    bandwidth_up: null
    options:
      log_level: null
      pcap_directory: null
      pcap_capture_size: 65535 B
  server:
    network_node_id: 0
    processes:
    - path: h_server
      args: '8888'
      environment: ''
      quantity: 1
      start_time: 1 sec
      stop_time: null
    ip_addr: null
    quantity: 1
    bandwidth_down: null
    bandwidth_up: null
    options:
      log_level: null
      pcap_directory: null
      pcap_capture_size: 65535 B
